#include "lexer.hpp"

enum JavaTokens
{
    Abstract=200,
    Assert,
    Boolean,
    Break,
    Byte,
    Case,
    Catch,
    Char,
    Class,
    Const,
    Continue,
    Default,
    Do,
    Double,
    Else,
    Enum,
    Extends,
    Final,
    Finally,
    Float,
    Identifier,  // Note: This must be after the keywords so they take precedence
    DecimalIntegerLiteral,
    HexIntegerLiteral,
    OctalIntegerLiteral,
    BinaryIntegerLiteral,
    DecimalFloatingPointLiteral,
    HexadecimalFloatingPointLiteral,
    CharaterLiteral,
    StringLiteral,
    BooleanLiteral,
    NullLiteral,
    OpenParen,
    CloseParen,
    OpenBrace,
    CloseBrace,
    OpenSquare,
    CloseSquare,
    SemiColon,
    Comma,
    Dot,
    DotDotDot,
    At,
    ColonColon,
    Eq,
    Gt,
    Lt,
    Excl,
    Minus,
    Question,
    Colon,
    Arrow,
    EqEq,


};

extern feiparser::char_lexer javalexer;
